name: Deno Bundle

on:
  push:
    paths:
      - "scripts/**"
      - ".github/workflows/deno-bundle.yml"
  pull_request:
    paths:
      - "scripts/**"
      - ".github/workflows/deno-bundle.yml"

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Show directory structure for debugging
        run: ls -lR scripts/

      - name: Bundle embassy.ts to embassy.js
        run: deno bundle scripts/embassy.ts scripts/embassy.js

      - name: Show output file
        run: ls -l scripts/embassy.js
