name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['main', 'master']
  push:
    paths-ignore: ['*.md']
    branches: ['main', 'master']

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export DENO_INSTALL="$HOME/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          echo "DENO_INSTALL=$DENO_INSTALL" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV
          deno --version

      - name: Cache Deno dependencies
        run: |
          export PATH="$DENO_INSTALL/bin:$PATH"
          # Pre-cache dependencies by running deno with network retry settings
          deno cache --reload scripts/dependencies.ts || echo "Initial cache attempt failed, continuing..."

      - name: Build the service package
        id: build
        run: |
          start-sdk init
          make
          PACKAGE_ID=$(yq -oy ".id" manifest.*)
          echo "package_id=$PACKAGE_ID" >> $GITHUB_ENV
          printf "\n SHA256SUM: $(sha256sum ${PACKAGE_ID}.s9pk) \n"
        shell: bash

      - name: Upload .s9pk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package_id }}.s9pk
          path: ./${{ env.package_id }}.s9pk
